### PR TITLE
Club Rep permissions

### PR DESCRIPTION
**Pull request by Sergeyvna**
When club rep has logged in, the additional account tab should be displayed to see monthly statements, the booking form should display only the student ticket + changed the maximum quantity of tickets to purchase to 10.

### CODE REVIEW

**Review by KayleeWilliams — APPROVED** [review]
Looks good, I will merge it into a separate branch to ensure it works with the new structure.

**Comment by j2-hore** [comment]
Ok. Thanks. Is it missing anything?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by j2-hore** [comment]
If it is then I'll take another look tomorrow.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by ryan-morgan9 — APPROVED** [review]
This looks good to me and cannot see any errors. I'll try to run it on my machine soon.

**Comment by j2-hore** [comment]
Ok. Good to know. It's only a starting point, but I will look at it some more tomorrow if necessary.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
