### PR TITLE
Kaylee/booking-ticket-models

### PR DESCRIPTION
**Pull request by KayleeWilliams**
Created models for ticket & booking.

### CODE REVIEW

**Review by Sergeyvna — COMMENTED** [review]
I was thinking that maybe instead of using customer name and email it would be better to have a separate customer model and then link it to the booking model?

**Comment by j2-hore** [comment]
I’ve added my club information to my own copy of the database. I’ll share it in the session tomorrow.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KayleeWilliams** [comment]
> I was thinking that maybe instead of using customer name and email it would be better to have a separate customer model and then link it to the booking model?

I thought we'd only do an account system for club reps and the managers I don't think there was a requirement for users to have an account. Maybe worth discussing in more detail tomorrow?

**Comment by KayleeWilliams** [comment]
Added a separate user model to the booking model based on @Sergeyvna's feedback.

**Comment by Sergeyvna** [comment]
To merge the pull request we need to somehow fix the occured conflict, but I am not susre how

**Comment by ryan-morgan9** [comment]
All the models look good to me!

**Review by ryan-morgan9 — APPROVED** [review]
These models look good to me!

**Pull request merged**
